name: dia_static
description: The middleware for Dia http server, for serving static files. Make Dia in webserver for static content).
version: 0.1.0
homepage: https://github.com/unger1984/dia_static

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dia: ^0.1.0
  path: ^1.8.0
  mime: ^1.0.0
  convert: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  http: ^0.13.1
